debug: true

logging:
  level:
    org:
      springframework.security.oauth2: DEBUG

# Define the port where the API gateway server will be running
server:
  port: 8765
  session:
    cookie:
      name: SESSIONID      

authserver:
  hostname: localhost
  port: 8088
  contextPath: oauth-server
    
checkTokenUrl: http://${authserver.hostname}:${authserver.port}/oauth/check_token

zuul:
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  ignored-patterns: /heart-beat**
  debug:
    request: true
  routes:
    me:
      path: /me/**
      stripPrefix: true
      url: http://${authserver.hostname}:${authserver.port}/me         
    login: 
      path: /login/**
      stripPrefix: true
      url: http://${authserver.hostname}:${authserver.port}/oauth/token

security:
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://${authserver.hostname}:${authserver.port}/oauth/token
      userAuthorizationUri: http://${authserver.hostname}:${authserver.port}/oauth/authorize
      clientId: poc-spa-client
      clientSecret: poc-spa-client
      scope: api_access, isMemberOf, mail, givenName, uid
    resource:
      userInfoUri: not-used
      preferTokenInfo: true
    
ribbon:
  ReadTimeout: 60000
        